Badges
EvilJadeon/TestGuru pull request #26
Opened 2022-01-28 11:16 UTC by EvilJadeon

Разработайте функционал который позволит пользователям получать бэйджи (награды) за успешное прохождение тестов.

Бэйджи представляются моделью Badge
Пользователь может получать один и тот же бэйдж более одного раза
Бэйдж обязательно содержит атрибуты:
    Название
    Имя файла с изображением (Делать загрузку изображений не нужно. Это может быть статический файл с изображением который вручную добавляется в проект. Либо это может быть любой URL с изображением бэйджа)
Выдача бэйджов происходит автоматически после завершения теста
Управление бэйджами осуществляется администратором
При создании бэйджа администратор также назначает правило которое определяет порядок выдачи бэйджа. Примеры правил:
    Выдать бэйдж после успешного прохождения всех тестов из категории Backend
    Выдать бэйдж после успешного прохождения теста с первой попытки
    Выдать бэйдж после успешного прохождения всех тестов определённого уровня
Допускается что критерии правил заданы заранее, например на уровне атрибутов модели
Пользователь в любой момент времени может посмотреть список всех существующих и заработанных бэйджей

2022-01-28 20:04 UTC, BubuntuClu requested changes

2022-01-28 20:04 UTC, BubuntuClu commented on app/views/badges/index.html.erb
> +  <%= render current_user.badges.order(created_at: :desc)  %>
почему тут этот код а не @budges?

2022-01-28 20:04 UTC, BubuntuClu commented on db/migrate/20220126151817_create_badges.rb
> +      t.integer :rule, null: false, default: 0
зачем дефолтное значение задавать для правила?

2022-01-28 20:24 UTC, EvilJadeon commented on app/views/badges/index.html.erb
> +  <%= render current_user.badges.order(created_at: :desc)  %>
потому что отображаю только баржи, принадлежащие одному юзеру

2022-01-28 20:25 UTC, EvilJadeon commented on db/migrate/20220126151817_create_badges.rb
> +      t.integer :rule, null: false, default: 0
Чтобы потом опереться на это дефолтное значение (типа награда еще не добавлена) и выводить соответствующее сообщение

2022-02-17 07:15 UTC, BubuntuClu requested changes

2022-02-17 07:15 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  before_validation :before_validation_set_current_question, on: :create
нет, это не решение. колбэк вызываться должен всегда, так как ты там выставляешь или первый или след вопрос

2022-02-17 07:15 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    self.current_question = next_question
в одном из заданий ты это убирал. так что не стоит возвращать

2022-02-17 07:15 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    update!(successfull: true)
бэнг метод без обработчика, нельзя так делать

2022-02-17 07:15 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    find_tests = Test.where(category_id: @test.category_id).count
почему тут идет фильтрация по категории из текущего теста, а не из беджа? так же храни в бейдже название категории, а не ID. администратор сайта задолбается запоминать ID категорий, а вот названия сможет. + у тебя есть метод на нахождение тестов по имени категории

2022-02-17 07:15 UTC, BubuntuClu commented on app/services/badge_service.rb
> +                              .where('test_passages.user_id = ? and test_passages.test_id = ? and test_passages.successfull = ? and tests.category_id = ?',
`test_passages.successfull = ?` зачем тут параметр? ты планируешь когда-то тут использовать что-то кроме `true`?

2022-02-17 07:15 UTC, BubuntuClu commented on app/services/badge_service.rb
> +                              .where('test_passages.user_id = ? and test_passages.test_id = ? and test_passages.successfull = ? and tests.category_id = ?',
ну и параметр категории будет строка с названием

2022-02-17 07:15 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    find_test_passages = TestPassage.where('test_id = ? and user_id = ? and successfull = ?', @test_passage.test_id, @test_passage.user_id, true).distinct.count
запрос неправильный. он при наличии плохих попыток выдаст бейдж при первом успешном прохождении. смысл метода, пройти тест с первого раза, а не первый успешный

2022-02-17 07:15 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    find_tests = Test.where(level: @test.level).count
тут надо фильтровать по уровню из бейджа, а не из теста

2022-02-17 07:15 UTC, BubuntuClu commented on app/services/badge_service.rb
> +                              .where('test_passages.user_id = ? and test_passages.test_id = ? and test_passages.successfull = ? and tests.category_id = ?',
`test_passages.test_id = ?` ты фильтруешь по id теста? это зачем? ты же так получишь прохождения только одного конкретного теста, а не все

2022-02-17 07:15 UTC, BubuntuClu commented on app/services/badge_service.rb
> +                            .where('test_passages.user_id = ? and test_passages.test_id = ? and test_passages.successfull = ? and tests.level = ?',
о5 же вопрос к `and test_passages.test_id = ? and test_passages.successfull = ? `

2022-02-17 07:15 UTC, BubuntuClu commented on db/migrate/20220214094809_add_value_to_badge.rb
> +class AddValueToBadge < ActiveRecord::Migration[6.1]
ты в рамках текущего ПРа создаешь таблицу баджей, ты можешь вносить изменения в таблицу, пока не смержил. не надо плодить лишние миграции

2022-02-17 17:46 UTC, BubuntuClu requested changes

2022-02-17 17:46 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    find_success_test_passages = TestPassage.where(user: @user, test: @test, successfull: true).count
тут не нужен второй запрос на не успех. получи все прохождения. проверь текущее прохождение успешное ли?

2022-02-17 17:46 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    find_test_passages = Test.where(category: value)
запрос невалидный. открой `rails c` определи переменные `value` и `@user`. вставь запрос в консоль и порверь работу

2022-02-18 16:51 UTC, BubuntuClu approved these changes

2022-02-18 16:51 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    @test_passage.successfull == true && find_test_passages.count <= 1
`find_test_passages.count == 1`

2022-02-18 16:51 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    @test_passage.successfull == true && find_test_passages.count <= 1
если каким-то непонтным образом количество будет 0, то у тебя условие отработает)
`@test_passage.successfull == true` можно сократить до `@test_passage.successfull`, поле хранит булеан значения. оно будет или `true` или `false`. не надо сравнивать этот результат с `true`чтобы получить результат проверки
в итоге ` @test_passage.successfull && find_test_passages.count == 1`

2022-02-18 19:28 UTC, merged